# Generated by Django 6.0a1 on 2025-11-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza1', models.ImageField(upload_to='poze/')),
                ('poza2', models.ImageField(upload_to='poze/')),
            ],
        ),
    ]
