# Generated by Django 6.0a1 on 2025-11-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_poze'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poze',
        ),
    ]
